add_newline = false


format = """
$username\
$directory\
$git_branch\
$character
"""

[character]                            # The name of the module we are configuring is "character"
character = "$"
#success_symbol = "[➜ ](bold green)" 


[directory]
truncation_length = 0
truncate_to_repo = false
style = "bold green"
use_logical_path = false


[cmd_duration]
disabled = true

[username]
show_always = true
style_user = "#ff6600"

[line_break]
disabled = true

[python]
disabled = true

[package]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

[golang]
disabled = true

[aws]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true
