local Plug = vim.fn['plug#']

vim.call('plug#begin', '~/.local/plugged')

Plug('nvim-lua/plenary.nvim')
Plug('nvim-telescope/telescope.nvim')
Plug('nvim-tree/nvim-web-devicons')
Plug('seblj/nvim-tabline')
Plug('nvim-lualine/lualine.nvim')
Plug('williamboman/mason.nvim')
Plug('williamboman/mason-lspconfig.nvim')
Plug('jay-babu/mason-nvim-dap.nvim')
Plug('mfussenegger/nvim-dap')
Plug('rcarriga/nvim-dap-ui')
Plug('neovim/nvim-lspconfig')
Plug('hrsh7th/vim-vsnip')
Plug('hrsh7th/cmp-vsnip')
Plug('hrsh7th/cmp-nvim-lsp')
Plug('hrsh7th/cmp-buffer')
Plug('hrsh7th/cmp-path')
Plug('hrsh7th/cmp-cmdline')
Plug('hrsh7th/nvim-cmp')
Plug('ptzz/lf.vim')
Plug('voldikss/vim-floaterm')
Plug('nvim-treesitter/nvim-treesitter')
Plug('https://github.com/chrisbra/Colorizer')
Plug('vimwiki/vimwiki')
Plug('romainl/vim-cool')
Plug('lewis6991/gitsigns.nvim')
Plug('jbyuki/nabla.nvim')
Plug('folke/which-key.nvim')


vim.call('plug#end')

require('nabakolu.plugins.config.lf')
require('nabakolu.plugins.config.telescope')
require('nabakolu.plugins.config.floaterm')
require('nabakolu.plugins.config.vimwiki')
require('nabakolu.plugins.config.lspconfig')
require('nabakolu.plugins.config.dap')
require('nabakolu.plugins.config.nvim-cmp')
require('nabakolu.plugins.config.treesitter')
require('nabakolu.plugins.config.lualine')
require('nabakolu.plugins.config.nvim-tabline')
require('nabakolu.plugins.config.colorizer')
require('nabakolu.plugins.config.gitsigns')
require('nabakolu.plugins.config.nabla')
require('nabakolu.plugins.config.which-key')
