local Plug = vim.fn['plug#']

vim.call('plug#begin', '~/.local/plugged')

Plug('williamboman/mason.nvim')
Plug('williamboman/mason-lspconfig.nvim')
Plug('neovim/nvim-lspconfig')
Plug('hrsh7th/vim-vsnip')
Plug('hrsh7th/cmp-vsnip')
Plug('hrsh7th/cmp-nvim-lsp')
Plug('hrsh7th/cmp-buffer')
Plug('hrsh7th/cmp-path')
Plug('hrsh7th/cmp-cmdline')
Plug('hrsh7th/nvim-cmp')
Plug('ptzz/lf.vim')
Plug('voldikss/vim-floaterm')
Plug('nvim-treesitter/nvim-treesitter', {['do'] = ':TSUpdate'})
Plug('https://github.com/chrisbra/Colorizer')
Plug('vimwiki/vimwiki')
Plug('romainl/vim-cool')
Plug('editorconfig/editorconfig-vim')

vim.call('plug#end')

require('nabakolu.plugins.config.lf')
require('nabakolu.plugins.config.floaterm')
require('nabakolu.plugins.config.vimwiki')
require('nabakolu.plugins.config.lspconfig')
require('nabakolu.plugins.config.nvim-cmp')
require('nabakolu.plugins.config.treesitter')
